export { AdminsRepository } from './admin.repository'
export { ChampionshipsDisciplinesRepository } from './championshipDiscipline.repository'
export { ChampionshipsJudgesRepository } from './championshipJudge.repository'
export { ChampionshipsRepository } from './championship.repository'
export { CoachesRepository } from './coach.repository'
export { DisciplinesRepository } from './discipline.repository'
export { JudgesRepository } from './judge.repository'
export { MembersRepository } from './member.repository'
export { PersonsRepository } from './person.repository'
export { PrizesRepository } from './prize.repository'
export { ResultsRepository } from './result.repository'
export { TeamsRepository } from './team.repository'
export { TitlesRepository } from './title.repository'
export { UsersRepository } from './user.repository'

